### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by giorg** [magespecialist/m2-MSP_CashOnDelivery#38]
hello,

in my <theme>/i18n/it_IT.csv I did put:

"You will be charged by an extra fee of %1 (+%2 taxes)","Ci sarà un costo ulteriore di %1"
"Cash on delivery","Pagamento in contrassegno"

but both in frontend and inside the email those strings don't get translated.
Any hint?

Thanks a lot

**Comment by phoenix128** [comment]
Make sure you followed all the translation steps required for Magento2:
- http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/xlate.html
- http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/translate_practice.html

You probably need a static content deploy

**Comment by giorg** [comment]
yes I did both collect-phrases and deploy, but no luck. Actually in this site I have *some other* (3 or 4, but mostly they are) string that don't get translation, I don't get why.
Maybe you have a further hint?

thanks a lot anyway

**Comment by phoenix128** [comment]
Unfortunately not, we should look into your Magento install to understand why.

I suggest you to make an online search, you will see a lot of people experiencing this kind of issue with different solutions.

I'm sorry, but this time we are unable to help you with this issue, because it is Magento2 related.
