### ISSUE TITLE
Manually Install Module Through FTP/Cpanel

### ISSUE THREAD

**Issue by mastermindcorporation** [magespecialist/m2-MSP_CashOnDelivery#41]
Can't really figure out a way to manually install this module through FTP/Cpanel.

Step 1. I have uploaded the Files to App/Code/MSP_Cashondelivery
Step 2. Run CLI Comman - $ php bin/magento module:enable MSP_Common

Error
Unknown module(s): 'MSP_Common'

**Comment by giacmir** [comment]
If you installed MSP_CashOnDelivery why do you try to enable MSP_Common?

MSP_Cashondelivery depends on MSP_Common that is a separate module that must be installed beforehand. You can find it here https://github.com/magespecialist/m2-MSP_Common

Nevertheless the preferred installation method is by using composer. Since you've access to CLI on you server I suggest to install composer and use it for all your dependency management.
