### ISSUE TITLE
Problem taxes admin sales and email order

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#9]
Hi,

there is a bug in order page (admin), email order, invoice with the price of Cash on delivery.
We have the correct price of COD in frontend but in order page (admin), email order, invoice we have the price excluding taxes.

Example
In CSV we have 2.46€

In frontend 2.46€ + 0.54 = 3€

In order page (admin), email order, invoice 
Cash On Delivery Amount: 	1,92 €
Cash On Delivery Tax: 	0,54 €

**Comment by phoenix128** [comment]
Hello @lucav90 ,
we are trying to reproduce this bug in our test environments.

Can we ask you how did you setup taxes in your store?

**Comment by wals06** [comment]
Hi,
i have the same problem.

I report the configuration of my tax page in italian, but all voices are in order

Classe tassa per la spedizione	-> 22
Classe Tassa predefinita per i prodotti	-> 22	
Classe Tassa predefinita per i clienti	-> Retail

Metodo di calcolo tasse basato su	-> Totale
Calcolo dell'imposta basato su	-> Indirizzo di fatturazione
Prezzi Catalogo	-> Incluse Tasse
Prezzi di spedizione	-> Escluse Tasse	
Applica Tassa cliente -> Prima dello sconto	
Applica sconto sui prezzi	-> Incluse Tasse
Applica Tassa su		-> Prezzo personalizzato se disponibile
Abilitare commercio oltre frontiera		-> No
	
Paese predefinito		-> Italia
Provincia Predefinita		-> *
Codice postale predefinito		-> *

Visualizzare i prezzi dei prodotti nel catalogo		-> Incluse Tasse
Visualizza i prezzi di spedizione		-> Incluse Tasse

Mostra prezzi		-> Incluse Tasse
Mostra Subtotale		-> Incluse Tasse
Mostra importo spedizione		-> Incluse Tasse
Includi tasse nel totale dell'ordine	-> NO
Mostra riepilogo completo tasse	-> SI
Mostra Subtotale tasse Zero	-> NO	

Mostra prezzi			-> Incluse Tasse
Mostra Subtotale		-> Incluse Tasse	
Mostra importo spedizione		-> Incluse Tasse	
Includi tasse nel totale dell'ordine	-> NO		
Mostra riepilogo completo tasse		-> NO	
Mostra Subtotale tasse Zero		-> NO	

Abilitare FPT		-> NO	
Visualizza prezzi In elenchi di prodotti		-> Only FTP	
Visualizza i prezzi nella Pagina di Visualizzazione Prodotto		-> Only FTP	
Visualizza Prezzi nei Moduli di Vendita		-> Only FTP	
Visualizza Prezzi nelle Email		-> Only FTP
Applicare Tassa al FPT		-> NO	
Includi FPT nel subtotale		-> NO

**Comment by ebaschiera** [comment]
I can confirm this issue. I am on Magento EE 2.1.3 .
In my opinion the problem is here: https://github.com/magespecialist/m2-MSP_CashOnDelivery/blob/master/Block/Info/CashOnDelivery.php#L37
Replacing 
`$amount = $order->getMspCodAmount() - $taxes;` 
with 
`$amount = $order->getMspCodAmount();` 
fixes the problem.

**Comment by phoenix128** [comment]
@ebaschiera , nice point. I think it depends on tax configuration. How did you configure Magento?

**Comment by ebaschiera** [comment]
In the end we modified the source code on two places: 
- https://github.com/magespecialist/m2-MSP_CashOnDelivery/blob/master/Block/Info/CashOnDelivery.php#L37 (as stated in my previous message)
- https://github.com/magespecialist/m2-MSP_CashOnDelivery/blob/master/Block/Sales/Cashondelivery.php#L51 , replacing
` 'value' => $this->getSource()->getBaseMspCodAmount() - $this->getSource()->getBaseMspCodTaxAmount(),`
with
`'value' => $this->getSource()->getBaseMspCodAmount(),`

But we got stuck with an issue at checkout, where taxes are not correctly calculated. Here is a screenshot:
![checkout summary](https://cloud.githubusercontent.com/assets/5667462/23219880/84165e00-f920-11e6-9e0c-f9def723edba.png)
We would expect a tax amount of € 72,53 instead of € 70,33 at the row "Italia (22%) 	70,33 €".
I still haven't found a fix for that.

Here it is the tax configuration screenshot:
![configuration 2f settings 2f stores 2f magento admin](https://cloud.githubusercontent.com/assets/5667462/23219673/056c817e-f920-11e6-87f8-3ff399184df8.png)

Thanks!

**Comment by synpatic** [comment]
The same problem can been seen also in PDF invoices:
The COD has been set 4 € and VAT is 24 %
Magento ver. 2.1.5 

Under 
**Payment Method**
Cash On Delivery Amount: 3,04 €
Cash On Delivery Tax: 0,96 €

**And in totals:**
Cash on delivery amount: 4,00 €
Cash on delivery tax: 0,96 €
